CREATE TABLE `solar_models` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`mw` int NOT NULL,
	`capexPerMW` int NOT NULL,
	`privateWireCost` int NOT NULL,
	`gridConnectionCost` int NOT NULL DEFAULT 0,
	`developmentPremiumPerMW` int NOT NULL,
	`opexPerMW` int NOT NULL,
	`opexEscalation` varchar(20) NOT NULL,
	`generationPerMW` varchar(20) NOT NULL,
	`degradationRate` varchar(20) NOT NULL,
	`projectLife` int NOT NULL,
	`discountRate` varchar(20) NOT NULL,
	`powerPrice` int NOT NULL,
	`lcoe` varchar(20),
	`irr` varchar(20),
	`paybackPeriod` varchar(20),
	`totalNpv` varchar(20),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `solar_models_id` PRIMARY KEY(`id`)
);
