CREATE TABLE `grid_connection_costs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`solarModelId` int NOT NULL,
	`agriculturalTrenchingMin` int NOT NULL DEFAULT 600000,
	`agriculturalTrenchingMax` int NOT NULL DEFAULT 1050000,
	`roadTrenchingMin` int NOT NULL DEFAULT 1200000,
	`roadTrenchingMax` int NOT NULL DEFAULT 2400000,
	`majorRoadCrossingsMin` int NOT NULL DEFAULT 300000,
	`majorRoadCrossingsMax` int NOT NULL DEFAULT 600000,
	`jointBaysMin` int NOT NULL DEFAULT 120000,
	`jointBaysMax` int NOT NULL DEFAULT 240000,
	`transformersMin` int NOT NULL DEFAULT 500000,
	`transformersMax` int NOT NULL DEFAULT 800000,
	`landRightsCompensationMin` int NOT NULL DEFAULT 20000,
	`landRightsCompensationMax` int NOT NULL DEFAULT 60000,
	`landRightsLegalMin` int NOT NULL DEFAULT 50000,
	`landRightsLegalMax` int NOT NULL DEFAULT 90000,
	`planningFeesMin` int NOT NULL DEFAULT 600,
	`planningFeesMax` int NOT NULL DEFAULT 1200,
	`planningConsentsMin` int NOT NULL DEFAULT 15000,
	`planningConsentsMax` int NOT NULL DEFAULT 40000,
	`constructionMin` int NOT NULL DEFAULT 3200000,
	`constructionMax` int NOT NULL DEFAULT 4200000,
	`softCostsMin` int NOT NULL DEFAULT 85000,
	`softCostsMax` int NOT NULL DEFAULT 190000,
	`projectMin` int NOT NULL DEFAULT 3300000,
	`projectMax` int NOT NULL DEFAULT 4400000,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grid_connection_costs_id` PRIMARY KEY(`id`)
);
